# -*- coding: utf-8 -*-
"""hugging_face_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbMbe5WRR5YjF1vtAvWGGJQ0dCivXaH1
"""

pip install scikit-learn pandas huggingface_hub

import joblib
import pandas as pd
from huggingface_hub import hf_hub_download
from sklearn.datasets import load_iris

# Download model from Hugging Face Hub
model_path = hf_hub_download(
    repo_id="Sonia2k5/decision_tree_flower",
    filename="iris_decision_tree.pkl"
)

# Load the model
model = joblib.load(model_path)

# Load Iris dataset to get target names
iris = load_iris()
class_names = iris.target_names

# Get user input
print("🌸 Enter Iris flower details:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))

# Prepare input for prediction
input_data = pd.DataFrame([[sepal_length, sepal_width, petal_length, petal_width]],
                          columns=iris.feature_names)

# Predict
predicted_class = model.predict(input_data)[0]
predicted_species = class_names[predicted_class]

# Output result
print(f"\n✅ Predicted species: {predicted_species}")