# -*- coding: utf-8 -*-
"""nlp_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mij6JdACySdIqlIGkcGAzUeMrSpZITfQ
"""

# Text Normalization from input.txt

# Step 1: Read from file
with open("/content/input.txt", "r") as file:
    text = file.read()

# Step 2: Convert to lowercase
normalized_text = text.lower()

# Step 3: Remove punctuation (keep only letters, numbers, and spaces)
normalized_text = "".join([char for char in normalized_text if char.isalnum() or char.isspace()])

# Step 4: Remove extra spaces
normalized_text = " ".join(normalized_text.split())

# Step 5: Print results
print("Original Text:", text)
print("Normalized Text:", normalized_text)