# -*- coding: utf-8 -*-
"""spacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb_eDe3Nf9F8ilCUheUJ60Cv4Vas0AmZ
"""

!pip install -U spacy
!python -m spacy download en_core_web_sm

import spacy
import os
from google.colab import files


# 🔹 Load spaCy model
nlp = spacy.load("en_core_web_sm")

# 🔹 Ask user for input method
choice = input("🟢 Enter 1 to upload a .txt file, or 0 to type manually: ").strip()

if choice == '1':
    print("📁 Please upload a .txt file:")
    uploaded = files.upload()
    filename = next(iter(uploaded))
    with open(filename, 'r') as f:
        text = f.read()
    print("📄 File uploaded successfully.\n")
else:
    text = input("📝 Enter your sentence: ")

# 🔍 POS tagging with spaCy
doc = nlp(text)

# 📄 Output
print("\n🔸 POS Tagging with Full Forms:\n")
print(f"{'Token':15} {'POS Tag':10} {'Description'}")
print("-" * 50)
for token in doc:
    tag_desc = spacy.explain(token.tag_)
    print(f"{token.text:15} {token.tag_:10} {tag_desc}")