# -*- coding: utf-8 -*-
"""stem_lemma_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17p8ZY0Dcfow3ioJrNGcIXvb-PIGAHVRz
"""

# Import necessary libraries
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required NLTK data
nltk.download('punkt')
nltk.download('wordnet')

# Read text from a file
with open("/content/input.txt", "r") as file:
    text = file.read()

print("Original Text:", text)

# ---- Stemming ----
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in text.split()]
print("Stemmed Words:", stemmed_words)

# ---- Lemmatization ----
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in text.split()]
print("Lemmatized Words:", lemmatized_words)

# Stop words removal demo code

import nltk
from nltk.corpus import stopwords
import re

# Download stopwords data
nltk.download('stopwords')

# Load English stop words
stop_words = set(stopwords.words('english'))

# Input text
text = input("Enter any text: ")

# Remove punctuation and split words
words = re.sub(r'[^\w\s]', '', text).split()

# Filter out stop words
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Filtered Words (without stop words):", filtered_words)