# -*- coding: utf-8 -*-
"""stemmer_lemitization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtM8_Ityi0WRwp4Hy05oD2oAmXWN9T0f
"""

# Import necessary libraries
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required NLTK data
nltk.download('punkt')
nltk.download('wordnet')

# Sample text
text = "they're playing and eating ice cream"

# ---- Stemming ----
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in text.split()]
print("Stemmed Words:", stemmed_words)

# ---- Lemmatization ----
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in text.split()]
print("Lemmatized Words:", lemmatized_words)