# -*- coding: utf-8 -*-
"""stopword.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tO_8B3ydpVbtuRF8j5wt3lNxXtI3-EY
"""

# Stop words removal demo code

import nltk
from nltk.corpus import stopwords
import re

# Download stopwords data
nltk.download('stopwords')

# Load English stop words
stop_words = set(stopwords.words('english'))

# Input text
text = input("Enter any text: ")

# Remove punctuation and split words
words = re.sub(r'[^\w\s]', '', text).split()

# Filter out stop words
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Filtered Words (without stop words):", filtered_words)