# -*- coding: utf-8 -*-
"""stopword_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8fD03pXEulEYY0J9Ler3Zd_9wYB-ogy
"""

import nltk
from nltk.corpus import stopwords
import re

# Download stopwords data
nltk.download('stopwords')

# Load English stop words
stop_words = set(stopwords.words('english'))

# Read text from file
with open("input.txt", "r") as file:
    text = file.read()

# Remove punctuation and split into words
words = re.sub(r'[^\w\s]', '', text).split()

# Filter out stop words
filtered_words = [word for word in words if word.lower() not in stop_words]

# Print result
print("Original Text:", text)
print("Filtered Words (without stop words):", filtered_words)