# -*- coding: utf-8 -*-
"""textblob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RB0IN3_kFm_OMVxtdYgBmXrsh_S6TnBB
"""

import nltk
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

try:
    nltk.data.find('averaged_perceptron_tagger')
except LookupError:
    nltk.download('averaged_perceptron_tagger')

try:
    nltk.data.find('taggers/averaged_perceptron_tagger_eng')
except LookupError:
    nltk.download('averaged_perceptron_tagger_eng')

print("NLTK data downloaded successfully!")

import nltk
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

print("'punkt_tab' corpus downloaded successfully!")

from textblob import TextBlob

text = "The quick brown fox jumps over the lazy dog"

blob = TextBlob(text)

for word, pos in blob.tags:
    print(word, pos)